engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
  - store/**
exclude_paths:
- 'lib/*'
- 'dist/*'
- 'build/*'
- 'nwjs/*'
- 'static/*'
- 'old/*'
- 'config/*'
- 'src/modv/sample-modules/*'
